/**
 * @file Config.h
 * @brief VideoParsing Config Header (auto generated by CMake)
 *
 * @author Abhijit Kundu
 */

#ifndef VIDEOPARSING_CORE_CONFIG_H_
#define VIDEOPARSING_CORE_CONFIG_H_

/// @brief Namespace containing all symbols of the VideoParsing library.
namespace vp {

} // end namespace vp

#endif // VIDEOPARSING_CORE_CONFIG_H_

